# Generated by Django 2.2.4 on 2019-11-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='permission.Permissions')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='role.Role')),
            ],
        ),
    ]
