# Generated by Django 2.2.4 on 2019-09-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
