# Generated by Django 2.2.4 on 2019-10-01 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('salary', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('doj', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.Department')),
            ],
        ),
    ]
