# Generated by Django 2.2.4 on 2019-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
