# Generated by Django 2.2.4 on 2019-08-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelist',
            name='email',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='employeelist',
            name='phone',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
