# Generated by Django 2.2.4 on 2019-08-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_auto_20190824_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelist',
            name='photo',
            field=models.FileField(default='', editable=False, upload_to=''),
        ),
    ]
