# Generated by Django 2.2.4 on 2019-11-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_auto_20191031_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='departments',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.DO_NOTHING, to='department.Department'),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='designations',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.DO_NOTHING, to='designation.Designation'),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='phone',
            field=models.CharField(blank=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='photo',
            field=models.FileField(blank=None, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='roles',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.DO_NOTHING, to='role.Role'),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='salary',
            field=models.IntegerField(blank=None),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='user_id',
            field=models.IntegerField(blank=None),
        ),
    ]
