# Generated by Django 2.2.4 on 2019-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_employeelist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
