# Generated by Django 2.2.4 on 2019-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_auto_20191102_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
