# Generated by Django 2.2.4 on 2019-08-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_auto_20190824_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelist',
            name='photo',
        ),
        migrations.AddField(
            model_name='employeelist',
            name='resume',
            field=models.FileField(default='', editable=False, upload_to='files/pdf/'),
        ),
    ]
