# Generated by Django 2.2.4 on 2019-08-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_auto_20190824_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='resume',
            field=models.FileField(upload_to='files/pdf/'),
        ),
    ]
