# Generated by Django 2.2.4 on 2019-08-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_auto_20190824_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelist',
            name='resume',
        ),
        migrations.AddField(
            model_name='employeelist',
            name='photo',
            field=models.FileField(blank=True, default='', editable=False, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
