# Generated by Django 2.2.4 on 2019-08-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_auto_20190824_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='photo',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
