# Generated by Django 2.2.4 on 2019-11-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_auto_20191102_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
