# Generated by Django 2.2.4 on 2019-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_auto_20191102_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='photo',
            field=models.FileField(default='documents/%Y/%m/%d/default.jpg', upload_to='documents/%Y/%m/%d/'),
        ),
    ]
