# Generated by Django 2.2.4 on 2019-11-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0009_auto_20191102_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='roles',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='role.Role'),
        ),
    ]
