# Generated by Django 2.2.4 on 2019-10-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='position',
            new_name='name',
        ),
    ]
